sudo: required
language: generic

services:
  - docker

before_install:
#  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
#  - sudo service docker restart
  - docker build -t cgiardin6d3947/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cgiardin6d3947/react-test npm test

after_success:
  - docker build -t cgiardin6d3947/multi-server ./server
  - docker build -t cgiardin6d3947/multi-worker ./worker
  - docker build -t cgiardin6d3947/multi-client ./client
  - docker build -t cgiardin6d3947/multi-nginx ./nginx
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push cgiardin6d3947/multi-server
  - docker push cgiardin6d3947/multi-worker
  - docker push cgiardin6d3947/multi-client
  - docker push cgiardin6d3947/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env" 
  bucket_name: "elasticbeanstalk-us-east-2-353663474754"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY